[graphite]
	address = "192.168.99.100:2003" # running sitespeedio/graphite on OSX with docker-machine

[datadog]

	api_key = "my-secret-key" # Datadog API key required.

[statsdaemon]

	address = "docker.local:8125"

[aws]

	availability_zone = "ap-southeast-2b"

